workflows:
  my-workflow:
    working_directory: php
    scripts:
      - name: Build jtraulle/php
        working_directory: php/8.1/8.1-fpm-alpine3.15
        script: docker build . -t jtraulle/php:8.1-fpm-alpine3.15-arm64
