workflows:
  my-workflow:
    working_directory: php
    scripts:
      - name: Build jtraulle/php
        working_directory: php/8.1/8.1-fpm-alpine3.15
        script: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install docker
          docker build . -t jtraulle/php:8.1-fpm-alpine3.15-arm64
